defmodule Offtherecord.Repo.Migrations.AddCategories do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:posts) do
      add :category_id, :uuid
    end

    create table(:categories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:posts) do
      modify :category_id,
             references(:categories,
               column: :id,
               name: "posts_category_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:categories) do
      add :name, :text, null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "categories_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:categories, [:user_id, :name],
             name: "categories_unique_name_per_user_index"
           )
  end

  def down do
    drop_if_exists unique_index(:categories, [:user_id, :name],
                     name: "categories_unique_name_per_user_index"
                   )

    drop constraint(:categories, "categories_user_id_fkey")

    alter table(:categories) do
      remove :updated_at
      remove :inserted_at
      remove :user_id
      remove :name
    end

    drop constraint(:posts, "posts_category_id_fkey")

    alter table(:posts) do
      modify :category_id, :uuid
    end

    drop table(:categories)

    alter table(:posts) do
      remove :category_id
    end
  end
end
