defmodule Offtherecord.Repo.Migrations.AddVectorToPosts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:posts) do
      add :full_text_vector, :vector, size: 3072
    end
  end

  def down do
    alter table(:posts) do
      remove :full_text_vector
    end
  end
end
